---
title: "Data Analysis 2"
author: "Phoebe Lu, Matthew Coates, Cory Lumsdaine"
date: "12/10/2021"
output: html_document
---
How to interpret log transformed variables: https://stats.idre.ucla.edu/other/mult-pkg/faq/general/faqhow-do-i-interpret-a-regression-model-when-some-variables-are-log-transformed/


```{r Load libraries, message=F}
library(dplyr)
library(regclass)
library(MASS)
library(ggplot2)
library(grid)
library(gridExtra)
library(data.table)
```

```{r Initialization}
#Read in dataset
cdi <- read.csv('cdi_data.csv')
#Create new crimes/1000 variable
cdi$crm_1000 <- (cdi$crimes/cdi$pop)*1000
hist(cdi$crm_1000)
#Factor region, rename variables, and set South as reference population (largest)
cdi$region_f <- as.factor(cdi$region)
levels(cdi$region_f) <- c("Northeast", "North Central", "South", "West")
barplot(table(cdi$region_f)) #South is the highest, so set as ref
cdi$region_f <- relevel(cdi$region_f, ref="South")
```

Variable selection: https://ucr.fbi.gov/hate-crime/2011/resources/variables-affecting-crime
* Variables in our dataset that are included in FBI's list are:
- % of population aged 18-34 (pop18)
- % high school graduates (hsgrad)
- % bachelor's degrees (bagrad)
- % below poverty level (poverty)
- % unemployment (unemp)
- per capita income (pcincome)
- Region (region)
* Outcome of interest: crime rate (crm_1000)
```{r EDA}
#Check for missing variables
sum(is.na(cdi)) #None are missing

#Mean & SD
mean(cdi$crm_1000) #57.29
sd(cdi$crm_1000) #27.33
mean(cdi$pop18) #28.57
sd(cdi$pop18) #4.19
mean(cdi$hsgrad) #77.56
sd(cdi$hsgrad) #7.02
mean(cdi$bagrad) #21.08
sd(cdi$bagrad) #7.65
mean(cdi$poverty) #8.72
sd(cdi$poverty) #4.65
mean(cdi$unemp) #6.60
sd(cdi$unemp) #2.34
mean(cdi$pcincome) #18561.5
sd(cdi$pcincome) #4059.192

#Correlations
continuous_vars <- cdi %>% dplyr::select(pop18, hsgrad, bagrad, poverty, unemp, pcincome,crm_1000)
pairs(continuous_vars) #visualize pairwise correlations
cors <- all_correlations(continuous_vars) #Pearson's correlation coefficients
cors
##Strongest correlations are:
##Hsgrad*bagrad = 0.71; hsgrad*poverty=-0.69, bagrad*pcincome = 0.695

#Normality
hist(cdi$pop18) #normal
hist(cdi$hsgrad) #left skewed
hist(cdi$bagrad) #right skewed
hist(cdi$poverty) #right skewed
hist(cdi$unemp) #right skewed
hist(cdi$pcincome) #right skewed
hist(cdi$crm_1000) #right skewed

longplot <- data.table(copy(cdi))
longplot <- melt(longplot,id.vars=c("id","cty","state","region","region_f"))
histdat <- copy(longplot[variable %in% c("pop18","hsgrad", "bagrad","poverty","unemp","pcincome","crm_1000")])
histdat[,fact_var:=factor(variable,levels=c("pop18","hsgrad", "bagrad","poverty","unemp","pcincome","crm_1000"),
                          labels=c("Population Age 18-34 (%)","Adults Graduated HS (%)","Adults with Bachelor's Degree (%)","Population in Poverty (%)","Unemployed (%)","Income per Capita ($)","Serious Crime Rate (per 1,000)"))]

gg <- ggplot(histdat,aes(x=value)) + 
  geom_histogram() + theme_bw() + facet_wrap(~fact_var,scales="free") + ylab("Count") + 
  xlab("")
print(gg)

#Log transform skewed variables
cdi$log_bagrad<- log(cdi$bagrad)
cdi$log_poverty <- log(cdi$poverty)
cdi$log_unemp <- log(cdi$unemp)
cdi$log_pcincome <- log(cdi$pcincome)
cdi$log_crm_1000 <- log(cdi$crm_1000)

longplot <- data.table(copy(cdi))
longplot <- melt(longplot,id.vars=c("id","cty","state","region","region_f"))
histdat <- copy(longplot[variable %in% c("pop18","hsgrad", "log_bagrad","log_poverty","log_unemp","log_pcincome","log_crm_1000")])
histdat[,fact_var:=factor(variable,levels=c("pop18","hsgrad", "log_bagrad","log_poverty","log_unemp","log_pcincome","log_crm_1000"),
                          labels=c("Population Age 18-34 (%)","Adults Graduated HS (%) (exp)","Adults with Bachelor's Degree (%) (log)","Population in Poverty (%) (log)","Unemployed (%) (log)","Income per Capita ($) (log)","Serious Crime Rate (per 1,000) (log)"))]

gg <- ggplot(histdat,aes(x=value)) + 
  geom_histogram() + theme_bw() + facet_wrap(~fact_var,scales="free") + ylab("Count") + 
  xlab("")
print(gg)




## correlation matrix of plots (scatters and correlation coefficients)
## adapted from http://www.sthda.com/english/wiki/scatter-plot-matrices-r-base-graphs
# Correlation panel
panel.cor <- function(x, y){
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  r <- round(cor(x, y), digits=2)
  txt <- paste0("r = ", r)
  #cex.cor <- 0.8/strwidth(txt)
  text(0.5, 0.5, txt)
}
# Customize upper panel
upper.panel<-function(x, y){
  points(x,y, pch = 19)
}
# Create the plots

dcorr <- data.table(copy(cdi))
dcorr <- dcorr[,c("pop18", "hsgrad", "bagrad", "poverty", "unemp", "pcincome","crm_1000"),with=F]


pairs(dcorr[,c("pop18", "hsgrad", "bagrad", "poverty", "unemp", "pcincome","crm_1000")], 
      lower.panel = panel.cor,
      upper.panel = upper.panel)


dcorr <- data.table(copy(cdi))
dcorr <- dcorr[,c("pop18", "hsgrad", "log_bagrad", "log_poverty", "log_unemp", "log_pcincome","log_crm_1000"),with=F]


pairs(dcorr[,c("pop18", "hsgrad", "log_bagrad", "log_poverty", "log_unemp", "log_pcincome","log_crm_1000")], 
      lower.panel = panel.cor,
      upper.panel = upper.panel)


```

```{r Simple regressions}
sr.1 <- lm(log_crm_1000 ~ pop18, data=cdi)
summary(sr.1) #p-value < 0.001, + estimate
sr.2 <- lm(log_crm_1000 ~ hsgrad, data=cdi)
summary(sr.2) #p-value = 0.474, - estimate == NOTE: update after not logging; 12/9 PL updated
sr.3 <- lm(log_crm_1000 ~ log_bagrad, data=cdi)
summary(sr.3) #p-value = 0.0586, + estimate
sr.4 <- lm(log_crm_1000 ~ log_poverty, data=cdi)
summary(sr.4) #p-value < 0.001, + estimate
sr.5 <- lm(log_crm_1000 ~ log_unemp, data=cdi) 
summary(sr.5) #p-value = 0.956, + estimate
sr.6 <- lm(log_crm_1000 ~ log_pcincome, data=cdi)
summary(sr.6) #p-value = 0.218, - estimate; 12/9 PL updated
sr.7 <- lm(log_crm_1000 ~ region_f, data=cdi)
summary(sr.7) #all p-value < 0.05, all - estimates
```

```{r Multivariate regressions}
#Highest significance to least
#pop18, log_poverty, region_f, log_bagrad, log_pcincome, hsgrad, log_unemp

#Manual stepwise regression (backwards)
#Total model
mr.1 <- lm(log_crm_1000 ~ pop18 + log_poverty + region_f + log_bagrad + log_pcincome + hsgrad + log_unemp, data=cdi)
summary(mr.1) #Adj r2: 0.4833
AIC(mr.1) #365.7378

#Total model-log_unemp is an improvement over Model 1
mr.2 <- lm(log_crm_1000 ~ pop18 + log_poverty + region_f + log_bagrad + log_pcincome + hsgrad, data=cdi)
summary(mr.2) #Adj r2: 0.4841
AIC(mr.2) #364.0604

#Total model-log_ump, hsgrad is an improvement over Model 2
mr.3 <- lm(log_crm_1000 ~ pop18 + log_poverty + region_f + log_bagrad + log_pcincome, data=cdi)
summary(mr.3) #Adj r2: 0.4853
AIC(mr.3) #362.0658

#Total model-log_ump, hsgrad is not an improvement over Model 3
mr.4 <- lm(log_crm_1000 ~ pop18 + log_poverty + region_f + log_bagrad, data=cdi)
summary(mr.4) #Adj r2: 0.4024; so want to keep log_pcincome
AIC(mr.4) #426.8241

#Total model-log_ump, hsgrad, log_bagrad is an improvement over Model 3; best model (all p-values < 0.05)
mr.5 <- lm(log_crm_1000 ~ pop18 + log_poverty + region_f + log_pcincome, data=cdi)
summary(mr.5) #Adj r2 = 0.4864
AIC(mr.5) #360.1058

#Final model is Model 5 (lowest AIC, highest Adj R2)
```

```{r Stepwise regressions}
intercept_only <- lm(log_crm_1000~1, data=cdi)
#forward stepwise regression with step() function from stats package
forward <- step(intercept_only, direction='forward', scope=formula(mr.1), trace=0)
forward$anova
forward$coefficients
AIC(forward)
#backward stepwise regression with step() function from stats package
backward <- step(mr.1, direction = 'backward', scope=formula(mr.1), trace=0)
backward$anova
backward$coefficients
AIC(backward)


#forward and backward stepwise regression with MASS package
full.model <- lm(log_crm_1000 ~ pop18 + hsgrad + log_bagrad + log_poverty + log_unemp + pcincome, data=cdi)
# Stepwise regression model
step.model <- stepAIC(full.model, direction = "both", 
                      trace = FALSE)
summary(step.model)
AIC(step.model)
```


